# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build using esbuild
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [19.9.0]
    steps:
    - uses: actions/checkout@v4
    - name: Build ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - name: Create Pull Request with built assets
      # This step will only run on pushes to the master branch,
      # to avoid creating PRs from PR validation builds if you uncomment the pull_request trigger above.
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      uses: peter-evans/create-pull-request@v6
      with:
        token: ${{ secrets.GITHUB_TOKEN }} # Uses the default GITHUB_TOKEN
        commit-message: "Auto-build: Add/Update distribution assets"
        committer: GitHub <actions@github.com> # Optional: customize committer
        author: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com> # Optional: customize author
        signoff: false # Optional: set to true if you want to sign off commits
        branch: "actions/update-dist-${{ github.run_id }}" # Creates a new branch for the PR
        delete-branch: true # Deletes the branch once the PR is merged or closed
        title: "chore: Update distribution assets"
        body: |
          Automatic build of distribution assets.
          This PR was created by the 'Build using esbuild and Create PR' GitHub Actions workflow.
        labels: |
          automated-pr
          build
        assignees: ${{ github.actor }} # Optional: assign the PR to the user who triggered the workflow
        # reviewers: user1,user2 # Optional: request reviews
        # team-reviewers: team1,team2 # Optional: request reviews from teams
        add-paths: | # Important: specify what to add to the commit
          dist/
        # If you have specific files and not a whole directory:
        # add-paths: |
        #   path/to/your/file.js
        #   path/to/your/otherfile.css
